sonar.organization=jbcom
sonar.projectKey=jbcom_persistence-drizzle
sonar.projectName=persistence-drizzle
sonar.sources=src
sonar.tests=tests
sonar.test.inclusions=tests/**/*.test.ts
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.exclusions=dist/**,docs/**,examples/**
